<?php $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block'); ?>
<div class="header-container">
     <div class="navbar-wrapper navbar-desktop">
         <div class="top-header">
              <div class="container-fluid shborder-bot onlylarg">
                   <div class="top-head-row">
                        <div class="col-lg-7 col-md-7 col-sm-7 col-xs-6 col-xss-12">
                              <?php 
                                   $block->setBlockId('csvape_topbar_help');
                                   if($block){
                                       echo $block->toHtml();
                                   }                              
                              ?>
                             
                        </div>
                         <div class="col-lg-5 col-md-5 col-sm-5 col-xs-6 col-xss-12">
                              <?php 
                                   $block->setBlockId('csvape_topbar_socials');
                                   if($block){
                                       echo $block->toHtml();
                                   }                              
                              ?>
                         </div>
                   </div>       
               </div>
               <div id="bar" class="container-fluid bottom-head-row">        
                    <div class="onlylarg">
                         <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6 col-xss-12">
                              <?php echo $this->getChildHtml("logo"); ?>
                         </div>
                         <div class="col-lg-7 col-md-7 col-sm-7 col-xs-6 col-xss-12 top-search">
                              <form>                             
                                   <input class="input-text form-control big-srcfield" type="text" placeholder="Search entire store here...">
                                   <button class="src-submit-btn"><span><i class="fa fa-search" aria-hidden="true"></i></span></button>
                              </form>
                         </div>
                         <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xss-12">
                              <div class="myacount">
                                   <a href="javascript:void(0)">My Account <span class="caret"></span></a>
                                    <div class="myacountDiv">
                                        <ul>
                                             <li><a href="javascript:void(0)">Your Account</a></li>
                                            <li><a href="javascript:void(0)">Your Orders</a></li>
                                            <li><a href="javascript:void(0)">Your Wish List</a></li>
                                            <li><a href="javascript:void(0)">Register</a></li>
                                            <li><a href="javascript:void(0)">Logout</a></li>
                                        </ul>
                                   </div>
                              </div>
                              <div class="mycart">
                                   <a href="javascript:void(0)">Cart (02)</a>
                              </div>
                         </div>
                    </div>
                   <div class="navbar-wrapper-mobile">		
                        <div class="container">
                             <div class="row">
                                  <div class="col-xs-2 paddsmll">
                                       <div class="cd-dropdown-wrapper">
                                       <a class="cd-dropdown-trigger cd-dropdown-trigger-custom" href="javascript:void(0)">
                                            <span class="menu-icon">
                                            <span class="line_one"></span>
                                            <span class="line_two"></span>
                                            <span class="line_three"></span>
                                       </span>
                                       <span class="menutxt"></span></a>
                   <nav class="cd-dropdown">
                        
                        <h2><a href="javascript:void(0)"><img src="images/csvape-logo-sm.png" alt="CSVAPE"></a></h2>
                             <a href="javascript:void(0)" class="cd-close">Close</a>
                             <ul class="cd-dropdown-content">
                             <li>
                               <form class="cd-search">
                                  <input type="search" placeholder="Search entire store here...">
                                  </form>
                                       </li>
                                  <li><a class="nav_home" href="#">Home</a></li>						
                                   
                               <li class="has-children">
                                            <a class="nav_ejuice" href="javascript:void(0)">Ejuice</a>
              
                                            <ul class="cd-secondary-dropdown ejuice-child-menu is-hidden" style="">
                                                 <li class="go-back"><a href="javascript:void(0)">Menu</a></li>							
                                                 <li class="has-children">
                                                      <a class="meghamneu-name" href="javascript:void(0)">Ejuice</a>                               
              
                                                      <ul class="is-hidden ejuice-child-cat">
                                                           <li class="go-back"><a href="javascript:void(0)">Ejuice</a></li>
                                                           <li class=""><a href="javascript:void(0)">All Ejuice</a></li>
                                                           <li class="has-children">
                                                                <a href="javascript:void(0)">Ejuice Brands</a>
                                                                <ul class="is-hidden ejuice-brand-list">
                                                                     <li class="go-back"><a href="#0">Ejuice Brands</a></li>
                                                                     <li class=""><a href="javascript:void(0)">View All Ejuice Brands</a></li>
                                                                     <li><a href="javascript:void(0)">Adam Bomb</a></li>
                                                          <li><a href="javascript:void(0)">Adope Life</a></li>
                                                          <li><a href="javascript:void(0)">American Pie Ejuice</a></li>
                                                          <li><a href="javascript:void(0)">Atlantis</a></li>
                                                          <li><a href="javascript:void(0)">ANML</a></li>
                                                          <li><a href="javascript:void(0)">Bad Drip</a></li>
                                                          <li><a href="javascript:void(0)">Bad Joos</a></li>
                                                          <li><a href="javascript:void(0)">Bam Bam E-Liquid</a></li>
                                                          <li><a href="javascript:void(0)">Bakers Man Ejuices</a></li>
                                                          <li><a href="javascript:void(0)">Bak-Lava</a></li>
                                                          <li><a href="javascript:void(0)">Baked Scoutz</a></li>
                                                          <li><a href="javascript:void(0)">Barista Brew Co.</a></li>
                                                          <li><a href="javascript:void(0)">Beetle Juice Vapors</a></li>
                                                          <li><a href="javascript:void(0)">B&B LA</a></li>
                                                          <li><a href="javascript:void(0)">Brewell Vapory</a></li>
                                                          <li><a href="javascript:void(0)">Broken Bottle</a></li>
                                                          <li><a href="javascript:void(0)">Boba Bae</a></li>
                                                          <li><a href="javascript:void(0)">BOBA Vapors</a></li>
                                                          <li><a href="javascript:void(0)">Bomb Sauce Ejuice</a></li>
                                                          <li><a href="javascript:void(0)">Bubbles Gum</a></li>
                                                                </ul>
                                                           </li>
                                                           <li class="has-children">
                                                                <a href="javascript:void(0)">Flavor Profile</a>
              
                                                                <ul class="is-hidden">
                                                                     <li class="go-back"><a href="#0">Ejuice</a></li>
                                                          <li class=""><a href="javascript:void(0)">View All Flavor Profile</a></li>
                                                          <li><a href="javascript:void(0)">Fruity Flavors</a></li>									
                                                          <li><a href="javascript:void(0)">Candy Flavors</a></li>
                                                          <li><a href="javascript:void(0)">Drink Flavors</a></li>
                                                          <li><a href="javascript:void(0)">Dessert Flavors</a></li>									
                                                          <li><a href="javascript:void(0)">Menthol Flavors</a></li>
                                                          <li><a href="javascript:void(0)">Cafe Flavors</a></li>
                                                          <li><a href="javascript:void(0)">Tobacco Flavors</a></li>
                                                                </ul>
                                                           </li>									
                                                      </ul>
                                                      <a class="meghamenuImg" href="javascript:void(0)"><img src="images/dealoftheday.jpg" alt="CSVAPE"><span>Buy Now</span></a>
                                                 </li>
              
                                            </ul> <!-- .cd-secondary-dropdown -->
                                       </li>
                                              
                                   <li class="has-children">
                                                 <a class="nav_mods" href="javascript:void(0)">Mods</a>
                                                 <ul class="cd-secondary-dropdown mods-child-ul is-hidden" style="">
                                                      <li class="go-back"><a href="javascript:void(0)">Menu</a></li>   
                                                      <li><a class="meghamneu-name mods-tt" href="javascript:void(0)">Mods</a></li>
                                                      <li class=""><a href="javascript:void(0)">View All Mods</a></li>
                                                      <li><a href="javascript:void(0)">Box Mods</a></li>
                                                      <li><a href="javascript:void(0)">Variable Voltage Mods</a></li>
                                                      <li><a href="javascript:void(0)">Mechanical Mods</a></li>
                                                      <a class="meghamenuImg" href="javascript:void(0)"><img src="images/meghamenumods.jpg" alt="CSVAPE"><span>Buy Now</span></a>
                                                 </ul> 
                                            </li>
                               <li class="has-children">
                                                 <a class="nav_accessories" href="#javascript:void(0)">Accessories</a>
                                                 <ul class="cd-secondary-dropdown accessories-child-ul is-hidden">
                                                      <li class="go-back"><a href="javascript:void(0)">Menu</a></li>
                                                      <li><a class="meghamneu-name mods-tt" href="javascript:void(0)">Accessories</a></li>
                                                      <li class=""><a href="javascript:void(0)">View All Accessories</a></li>
                                                      <li><a href="javascript:void(0)">Replacement Atomizer Coils</a></li>
                                                      <li><a href="javascript:void(0)">Battery Chargers</a></li>
                                                      <li><a href="javascript:void(0)">Batteries</a></li>
                                                      <li><a href="javascript:void(0)">Apparel</a></li>
                                                      <li><a href="javascript:void(0)">Cotton Wicks</a></li>
                                                      <li><a href="javascript:void(0)">Low Resistance Wires</a></li>
                                              <li><a href="javascript:void(0)">Coil Build Tools</a></li>
                                                      <a class="meghamenuImg" href="javascript:void(0)"><img src="images/accessoriesdeal.jpg" alt="CSVAPE"><span>Buy Now</span></a>
                                                 </ul> 
                                            </li> 
                                  <li><a class="nav_tanks" href="javascript:void(0)">Tanks</a></li>                             
                                       <li><a class="nav_rda" href="javascript:void(0)">RDA</a></li>						
                                       <li><a class="nav_starterkits" href="javascript:void(0)">Starter Kits</a></li>
                                       <li><a class="nav_podsystem" href="javascript:void(0)">Pod System</a></li>
                                  <li><a class="nav_vgod" href="javascript:void(0)">VGOD</a></li>
                                  <li><a class="nav_deal" href="javascript:void(0)">Deal of The Day</a></li>
                                  </ul> 
                             </nav> 		
                             
                        </div>
                                  </div>
                                  <div class="col-xs-5 paddsmll logodiv">
                                       <a class="mobile-logo" href="#"><img src="images/csvape-logo-sm.png" alt="CSVAPE"></a>
                                  </div>
                                  
                                  <div class="col-xs-5 paddsmll cust-div">
                                                                
                                       <a class="user-menu" href="javascript:void(0)"><i class="fa fa-user" aria-hidden="true"></i> <span class="caret"></span></a>
                                            <div class="user-profile">
                                                 <ul>
                                                      <li><a href="javascript:void(0)">Your Account</a></li>
                                              <li><a href="javascript:void(0)">Your Orders</a></li>
                                              <li><a href="javascript:void(0)">Your Wish List</a></li>
                                              <li><a href="javascript:void(0)">Register</a></li>
                                              <li><a href="javascript:void(0)">Logout</a></li>
                                                 </ul>
                                            </div>
                                       
                                       
                                       <a class="contact-menu" href="tel:+1855-775-8273"><i class="fa fa-phone" aria-hidden="true"></i></a>					
                                       <div class="contactDiv-mob">
                                            <ul>
                                                 <li><i class="fa fa-phone" aria-hidden="true"></i> 033-65555065 / 9831649999</li>
                                                 <li><i class="fa fa-whatsapp" aria-hidden="true"></i> 9831649999</li>
                                                 <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i> care@prabhujionline.com</a></li>
                                            </ul>
                                       </div>
                                       
                                       <a class="user-cart" href="#"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                                       <div class="cart-div">
                                            <p>0 item(s) <i class="fa fa-inr" aria-hidden="true"></i> 0.00</p>
                                       </div>
                                       
                                  </div>
                                  
                             </div>
                        </div>
                        
                        
                        
                   </div>	
                    
                      </div>
         </div>	  
     </div>  
    
     
</div>
