    <div class="std">
        
        <section class="home-quickaccess">
            <h1 class="section-title"><span>Quick</span> Access</h1>
            	<div class="col-lg-6 col-sm-6">
                	<div class="row">
                     <div class="col-lg-6 col-sm-6 col-xs-6 col-xss-12">
                         <div class="vapekitbuilder">
                        <img src="<?php echo $block->getViewFileUrl('images/vapekit-builder.jpg'); ?>" alt="">
						<a class="vapekitbuilder-link" href="javascript:void(0)">Vape Kit Builder <i class="fa fa-angle-double-right" aria-hidden="true"></i>
</a>
                            <p>Learn how to build your own coils with your built kit! Understand how each tool works with ease.</p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-6 col-xs-6 col-xss-12">
                        	<div class="newvaping">
                        	<img src="<?php echo $block->getViewFileUrl('images/new2vaping.jpg'); ?>" alt="">
							<a class="newvaping-link" href="javascript:void(0)">Vape Kit Builder <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                            <p>If you’re new to vaping, let’s get you started on switching the habit! Check out our beginner devices!</p>
                            </div>
                        </div>
                    </div>
                </div>
    <div class="col-lg-6 col-sm-6">
         <div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 600px; height: 430px; background: #fff; overflow: hidden; ">       
        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left:0px; top: 0px; width: 600px; height: 300px;
            overflow: hidden;">
            <div>
                <a class="sl-item" href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/todays-deal-big.jpg'); ?>" alt="">
                 <div class="sl-caplink"><h3>Today's Deals</h3><span>Deal Now <i class="fa fa-play" aria-hidden="true"></i></span></div>
                </a>
                <div u="thumb"><img src="<?php echo $block->getViewFileUrl('images/todays-deal-sm.jpg'); ?>" alt=""><h5>Today's Deals</h5></div>
            </div>
            <div>
             <a class="sl-item" href="javascript:void(0)"> <img src="<?php echo $block->getViewFileUrl('images/top-elquid-big.jpg'); ?>" alt="">
             <div class="sl-caplink"><h3>Top E-liquid</h3><span>Explore Now <i class="fa fa-play" aria-hidden="true"></i></span></div>
             </a>
                <div u="thumb"><img src="<?php echo $block->getViewFileUrl('images/top-elquid-sm.jpg'); ?>" alt=""><h5>Top E-liquid</h5></div>
            </div>
            <div>
                <a class="sl-item" href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/todays-deal-big.jpg'); ?>" alt="">
                <div class="sl-caplink"><h3>Today's Deals</h3><span>Deal Now <i class="fa fa-play" aria-hidden="true"></i></span></div>
                </a>
                <div u="thumb"><img src="<?php echo $block->getViewFileUrl('images/top-devices-sm.jpg'); ?>" alt=""><h5>Top Devices</h5></div>
            </div>
            <div>
                <a class="sl-item" href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/todays-deal-big.jpg'); ?>" alt="">
                <div class="sl-caplink"><h3>Today's Deals</h3><span>Deal Now <i class="fa fa-play" aria-hidden="true"></i></span></div>
                </a>
                <div u="thumb"><img src="<?php echo $block->getViewFileUrl('images/featured-pro-sm.jpg'); ?>" alt=""><h5>Featured Products</h5></div>
            </div>
            <div>
                <a class="sl-item" href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/todays-deal-big.jpg'); ?>" alt="">
                <div class="sl-caplink"><h3>Today's Deals</h3><span>Deal Now <i class="fa fa-play" aria-hidden="true"></i></span></div>
                </a>
                <div u="thumb"><img src="<?php echo $block->getViewFileUrl('images/new-arrival-sm.jpg'); ?>" alt=""><h5>New Arrivals</h5></div>
            </div>
             
        </div>
        
        <!-- ThumbnailNavigator Skin Begin -->
        <div u="thumbnavigator" class="jssort14" style="position: absolute; width: 600px; height: 120px; left:0px; bottom: 0px;background:#fff;">
            <!-- Thumbnail Item Skin Begin -->
            <style>
                /* jssor slider thumbnail navigator skin 14 css */
                /*
                .jssort14 .p            (normal)
                .jssort14 .p:hover      (normal mouseover)
                .jssort14 .pav          (active)
                .jssort14 .pav:hover    (active mouseover)
                .jssort14 .pdn          (mousedown)
                */
                .jssort14 .w, .jssort14 .phv .w
                {
                	cursor: pointer;
                	position: absolute;
                	WIDTH: 100%;
                	HEIGHT: 100%;
                	background-color: transparent;
                }
                .jssort14 .pdn .w, .jssort14 .pav .w, .jssort14 .p:hover .w
                {
                	background-color: transparent;
                }
                .jssort14 .c
                {
                    color: #000;
                    font-size:13px;
                	background-color: transparent;               	
                	
                }
                .jssort14 .p:hover .c, .jssort14 .phv .c, .jssort14 .pav:hover .c, .jssort14 .pav .c
                {
                	transition: none;
                    -moz-transition: none;
                    -webkit-transition: none;
                    -o-transition: none;
                }
                .jssort14 .pav .c
                {
                	
                }
                .jssort14 .p:hover .c, .jssort14 .phv .c, .jssort14 .pav:hover .c
                {
                	
                }
            </style>
      <div u="slides" style="cursor: move; width:600px; top:0px; left:0px;">
        <div u="prototype" class="p" style="POSITION: absolute; WIDTH: 120px; HEIGHT: 120px; TOP: 0; LEFT: 0; padding:0px; background:#fff;">
          <div class=w>
           <div u="thumbnailtemplate" class="c" style=" WIDTH: 100%; HEIGHT: 120px; position:absolute; TOP: 0; LEFT: 0; line-height:23px; text-align:center;">
                    </div>
                    </div>
                  </div>
                </div>
            </div>
            
           
        </div>
                </div>
        </section>
    
    <section class="Homepopular-cat">
         <h2 class="section-title"><span>Popular</span> Categories <a class="sec-viewall" href="javascript:void(0)">View all</a></h2>
    	<div class="owl-carousel owl-theme popularCat">
            <div class="item">
              <img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>E-Liquids</h4>
            </div>
            <div class="item">
             <img src="<?php echo $block->getViewFileUrl('images/popular-cat-podsystem.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Pod Systems</h4>
            </div>
            <div class="item">
             <img src="<?php echo $block->getViewFileUrl('images/popular-cat-mods.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Mods</h4>
            </div>
            <div class="item">
            <img src="<?php echo $block->getViewFileUrl('images/popular-cat-tanks.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Tanks</h4>
            </div>
            <div class="item">
              <img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>E-Liquids</h4>
            </div>
            <div class="item">
             <img src="<?php echo $block->getViewFileUrl('images/popular-cat-podsystem.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Pod Systems</h4>
            </div>
            <div class="item">
             <img src="<?php echo $block->getViewFileUrl('images/popular-cat-mods.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Mods</h4>
            </div>
            <div class="item">
            <img src="<?php echo $block->getViewFileUrl('images/popular-cat-tanks.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Tanks</h4>
            </div>
            <div class="item">
              <img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>E-Liquids</h4>
            </div>
            <div class="item">
             <img src="<?php echo $block->getViewFileUrl('images/popular-cat-podsystem.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Pod Systems</h4>
            </div>
            <div class="item">
             <img src="<?php echo $block->getViewFileUrl('images/popular-cat-mods.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Mods</h4>
            </div>
            <div class="item">
            <img src="<?php echo $block->getViewFileUrl('images/popular-cat-tanks.jpg'); ?>" alt="">
              <a href="javascript:void(0)">View Details</a>
              <h4>Tanks</h4>
            </div>
          </div>
    </section>
 
 <section class="csvape-lifestyle">
   <h2 class="section-title"><span>Shop The CSVAPE </span>Lyfestyle</h2>
 	<div class="row">
    	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-xss-12">
        	<div class="lifestyle-block">
            	<img src="<?php echo $block->getViewFileUrl('images/csvape-lifestyle-vgod.jpg'); ?>" alt="">
                <div class="block-caption">
                	<p>Live the VGOD Lyfe with the exclusive VGOD line of products</p>
                    <p><a href="javascript:void(0)">Live Lyfe Now</a></p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-xss-12">
        	<div class="lifestyle-block">
            	<img src="<?php echo $block->getViewFileUrl('images/csvape-lifestyle-bestsellers.jpg'); ?>" alt="">
                <div class="block-caption">
                	<p>Live the VGOD Lyfe with the exclusive VGOD line of products</p>
                    <p><a href="javascript:void(0)">Live Lyfe Now</a></p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-xss-12">
        	<div class="lifestyle-block">
            	<img src="<?php echo $block->getViewFileUrl('images/csvape-lifestyle-brandspotlight.jpg'); ?>" alt="">
                <div class="block-caption">
                	<p>Live the VGOD Lyfe with the exclusive VGOD line of products</p>
                    <p><a href="javascript:void(0)">Live Lyfe Now</a></p>
                </div>
            </div>
        </div>
    </div>
 </section>       

<div class="dottedbg-divider">&nbsp;</div>       

<section class="two-column">
  <h2 class="center-title">Join Our Programs to Receive<br> <span>Saving, Benefits & More</span></h2>
	<div class="row">
    	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xss-12">
        	<div class="referralDiv">
            	<h3>REFERRAL PROGRAM</h3>
                <h4>HELP YOUR FRIENDS & FAMILY </h4>
                <h5>Switch the Habit</h5>
                <p>You have successfully switched the habit! Now tell a friend or family member and get rewards points for your referrals !</p>
                <a class="btn-big" href="javascript:void(0)">Reffer Now</a>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xss-12">
        	<div class="reawarDiv">
            	<h3>CSVAPE REWARDS</h3>
                <h4>COLLECT POINTS AS YOU SHOP</h4>               
                <p>Get the latest product releases, special discounts, etc, with your CSVAPE rewards</p>
                <a class="btn-big" href="javascript:void(0)">Get Rewards</a>
            </div>
        </div>
    </div>
</section>

<div class="dottedbg-divider">&nbsp;</div>

<section class="thnks-partner">
	 <h2 class="center-title">Special Thanks<br> <span>To Our Partners</span></h2>
     <div class="thnks-partner-blue">
     <div class="row">
     	<div class="col-lg-6 col-md-6 col-sm-6">
        	<h3>E-Liquid Brands</h3>
            <div class="proBrands">
            	<div class="owl-carousel owl-theme brandslider">
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand2.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand4.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand2.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand4.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand2.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand4.png'); ?>" alt=""></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
        	<h3>Product Brands</h3>
            <div class="proBrands">
            	<div class="owl-carousel owl-theme brandslider">
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand1.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand2.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand3.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand4.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand1.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand2.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand3.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand4.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand1.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand2.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand3.png'); ?>" alt=""></div>
                    <div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand4.png'); ?>" alt=""></div>
                </div>
            </div>
        </div>
     </div>
   </div>
</section> 

<section class="bottom-section">
	<div class="row">
    	<div class="col-lg-3 col-md-3 col-sm-3">
        	<div class="csvape-comunity">
            	<h3><span>CSVAPE</span> Community</h3>
                <div class="news-updte">
                	<h4>News Update</h4>
                    <img src="<?php echo $block->getViewFileUrl('images/newsimg.jpg'); ?>" alt="">
                    <h5>VGOD Product</h5>
                    <p>Check out VGOD’s new product on the market ready for enjoyment! The new product has been created to amaze all, and satisfy your taste bud cravings! Click for more information and learn what’s new from VGOD. <a href="javascript:void(0)">Read full</a></p>
                    <a class="mornews" href="#">More News</a>
                </div>
                 <div class="news-updte cspoll">
                	<h4>CSVAPE Poll</h4>                    
                    <p>How many cigarettes a day did you smoke before vaping?</p>
                    <form class="smkoking-poll">
                         <div class="form-group"><input type="radio"> <label>1-10 a day</label></div>
                          <div class="form-group"><input type="radio"> <label>11-20 a day</label></div>
                          <div class="form-group"><input type="radio"> <label>21+  a day</label></div>  
                        </form> 
                    <a class="mornews" href="#">More News</a>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-9">
        	<h3>Best Kept Secrets - Brands You Should Know</h3>
            <div class="row best-kept-secret">
            	<div class="col-lg-4 col-sm-4 col-md-4">
                <img src="<?php echo $block->getViewFileUrl('images/coilhip-logo.jpg'); ?>" alt="">
                	<p>Products Description here. Supreme Performance, Premim parts..etc..</p>
                    <a href="#">SHOP NOW</a>
                </div>
                <div class="col-lg-4 col-sm-4 col-md-4">
                    <img src="<?php echo $block->getViewFileUrl('images/flavor-drip.jpg'); ?>" alt="">
                	<p>Experience one of the most premium ejuice brands out there. Check out their famous strawberry shortcake!</p>
                    <a href="#">SHOP NOW</a>
                </div>
                <div class="col-lg-4 col-sm-4 col-md-4">
               		<img src="<?php echo $block->getViewFileUrl('images/vgod-black.jpg'); ?>" alt="">
                	<p>VGOD’s Mods and Atomizers designed for extravagant performance! Experience the world of VGOD and more...</p>
                    <a href="#">SHOP NOW</a>
                </div>
            </div>
            <div class="row buy-confidence">
            	<h4>BUY WITH CONFIDENCE</h4>
                <p>If you’re in the market for a new device, csvape.com specializes in making sure our customers are happy with their purchase. Ensuring the devices are authentic and ready to go, along with our incredible pricing, buying from us will make your day and more!</p>
            </div>
            
            <div class="row superior-service">
            	<h4>SUPERIOR SERVICE & PREMIUM QUALITY PRODUCTS</h4>
                <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
                	<div class="sp-block">
                    	<div class="icoBlock">
                        	<i class="fa fa-globe" aria-hidden="true"></i>
                        </div>
                        <div class="descBlock">
                        	<h1>30,000+</h1>
                            <p>WorldWide Customers</p>
                        </div>
                    </div>                    
                </div>
                 <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
                	<div class="sp-block">
                    	<div class="icoBlock">
                        	<i class="fa fa-star" aria-hidden="true"></i>
                        </div>
                        <div class="descBlock">
                        	<h1>4,000+</h1>
                            <p>Product Reviews</p>
                        </div>
                    </div>                    
                </div>
                 <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
                	<div class="sp-block">
                    	<div class="icoBlock">
                        	<i class="fa fa-eyedropper" aria-hidden="true"></i>
                        </div>
                        <div class="descBlock">
                        	<h1>300+</h1>
                            <p>E-Liquid Flavors</p>
                        </div>
                    </div>                    
                </div>
                 <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
                	<div class="sp-block">
                    	<div class="icoBlock">
                        	<img src="<?php echo $block->getViewFileUrl('images/vape-ico.png'); ?>" alt="">
                        </div>
                        <div class="descBlock">
                        	<h1>600+</h1>
                            <p>Vape Products</p>
                        </div>
                    </div>                    
                </div>                
            </div>
        </div>
    </div>
</section>      
        
      </div>   
